# Generated by Django 5.2.7 on 2025-11-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('clase', models.CharField(max_length=50, verbose_name='Clase')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('numero_pasaporte', models.CharField(max_length=50, verbose_name='Nº Pasaporte/DNI')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono_privado', models.CharField(blank=True, max_length=20, null=True)),
                ('movil', models.CharField(max_length=20, verbose_name='Móvil')),
                ('email_alumno', models.EmailField(max_length=254, verbose_name='Email del alumno')),
                ('email_padres', models.EmailField(max_length=254, verbose_name='Email de los padres')),
                ('profesion_padre', models.CharField(blank=True, max_length=100, null=True)),
                ('profesion_madre', models.CharField(blank=True, max_length=100, null=True)),
                ('edad_hermanos', models.CharField(blank=True, help_text='Ej: 12, 15', max_length=50, null=True)),
                ('edad_hermanas', models.CharField(blank=True, help_text='Ej: 10', max_length=50, null=True)),
                ('mascotas', models.CharField(blank=True, max_length=200, null=True, verbose_name='Mascotas (¿cuáles?)')),
                ('problemas_salud', models.TextField(blank=True, null=True, verbose_name='Problemas de salud (alergias, etc.)')),
                ('es_vegetariano', models.BooleanField(default=False, verbose_name='Soy vegetarian@')),
                ('preferencia_intercambio', models.CharField(choices=[('CHICO', 'Un chico'), ('CHICA', 'Una chica'), ('DA_IGUAL', 'Da igual')], default='DA_IGUAL', max_length=10, verbose_name='Como intercambio prefiero')),
                ('puedo_alojar_dos', models.BooleanField(default=False, verbose_name='Puedo alojar a dos alumnos')),
                ('interes_larga_duracion', models.BooleanField(default=False, verbose_name='Quisiera participar en larga duración (4º ESO)')),
                ('caracter', models.TextField(blank=True, verbose_name='Carácter (descríbete brevemente)')),
                ('deportes', models.TextField(blank=True, verbose_name='Mis deportes')),
                ('musica', models.TextField(blank=True, verbose_name='Música y grupos favoritos')),
                ('otros_hobbies', models.TextField(blank=True, verbose_name='Otros pasatiempos (leer, cine, etc.)')),
            ],
        ),
    ]
