# Generated by Django 5.2.8 on 2025-11-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='lactosa',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='recetasApp.lactosa'),
        ),
    ]
