# Generated by Django 5.2.8 on 2025-12-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetas',
            name='ingredientes',
            field=models.ManyToManyField(related_name='Ingredientes', through='recetasApp.IngredienteReceta', to='recetasApp.ingrediente'),
        ),
    ]
