# Generated by Django 5.2.7 on 2025-11-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('precio', models.IntegerField(default=0)),
                ('especificacion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.producto')),
            ],
            bases=('blog.producto',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.producto')),
            ],
            bases=('blog.producto',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.producto')),
            ],
            bases=('blog.producto',),
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.producto')),
            ],
            bases=('blog.producto',),
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='blog.cliente')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cpu')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.gpu')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ram')),
                ('ssd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ssd')),
            ],
        ),
    ]
